### ISSUE TITLE
Safari Zone 

### ISSUE THREAD

**Issue by AaronHibbett** [Vizualyse/PokemonInfiniteFusion-EnemyTypesMod#1]
Following error in the Safari zone, 

![image](https://github.com/user-attachments/assets/867110cf-44d7-40ff-af36-8bec07828c68)

Have fixed myself by just adding the following if statement to the \Data\Scripts\011_Battle\005_Battle scene\004_PokeBattle_SceneElements.rb file, inside the if @battler.opposes?(0) statement, disables the type checking in the safari zone

if @battler.respond_to?(:type1) && @battler.respond_to?(:type2) 
...
end

**Comment by Vizualyse** [comment]
I fixed this just 5 minutes before you raised the issue, thanks for suggesting a solution though
